/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "EmailApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "EmailBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "EmailDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmailQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
